/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.talentFlow.view;
import com.talentFlow.dao.DepartamentoDAO;
import com.talentFlow.model.Departamento;
import com.talentFlow.model.Empleado;
import com.talentFlow.config.DatabaseConnection;
import com.talentFlow.dao.EmpleadoDAO;
import com.talentflow.view.util.DepartamentoUIHelper;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author Pavilion X360
 */
public class EmpleadoFrame extends javax.swing.JFrame {
    DepartamentoDAO depDao = new DepartamentoDAO();
    private int idSeleccionadoParaActualizar = -1;
    private int idMemoria = -1;
    /**
     * Creates new form EmpleadoFrame
     */
    public EmpleadoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JTabbedPane();
        panelInicio = new javax.swing.JPanel();
        panelEmpleados = new javax.swing.JPanel();
        panelDepartamentos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreDepartamento = new javax.swing.JTextField();
        btnGuardarDepto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBuscarDepartamento = new javax.swing.JButton();
        btnEliminarDepartamento = new javax.swing.JButton();
        btnListarDepartamentos = new javax.swing.JButton();
        btnActualizarDepartamento = new javax.swing.JButton();
        lblInstruccion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        panel.addTab("Inicio", panelInicio);

        javax.swing.GroupLayout panelEmpleadosLayout = new javax.swing.GroupLayout(panelEmpleados);
        panelEmpleados.setLayout(panelEmpleadosLayout);
        panelEmpleadosLayout.setHorizontalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );
        panelEmpleadosLayout.setVerticalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        panel.addTab("Empleados", panelEmpleados);

        jLabel1.setText("Nombre del Departamento");

        btnGuardarDepto.setText("Guardar");
        btnGuardarDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDeptoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        btnBuscarDepartamento.setText("Buscar");
        btnBuscarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDepartamentoActionPerformed(evt);
            }
        });

        btnEliminarDepartamento.setText("Eliminar");
        btnEliminarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDepartamentoActionPerformed(evt);
            }
        });

        btnListarDepartamentos.setText("Listar");
        btnListarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDepartamentosActionPerformed(evt);
            }
        });

        btnActualizarDepartamento.setText("Actualizar");
        btnActualizarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDepartamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDepartamentosLayout = new javax.swing.GroupLayout(panelDepartamentos);
        panelDepartamentos.setLayout(panelDepartamentosLayout);
        panelDepartamentosLayout.setHorizontalGroup(
            panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepartamentosLayout.createSequentialGroup()
                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDepartamentosLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDepartamentosLayout.createSequentialGroup()
                                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelDepartamentosLayout.createSequentialGroup()
                                        .addComponent(btnGuardarDepto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBuscarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelDepartamentosLayout.createSequentialGroup()
                                        .addComponent(btnEliminarDepartamento)
                                        .addGap(42, 42, 42)
                                        .addComponent(btnListarDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(btnActualizarDepartamento)))
                                .addGap(50, 50, 50))))
                    .addGroup(panelDepartamentosLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(lblInstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        panelDepartamentosLayout.setVerticalGroup(
            panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepartamentosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblInstruccion)
                .addGap(18, 18, 18)
                .addGroup(panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarDepto)
                    .addComponent(btnBuscarDepartamento)
                    .addComponent(btnEliminarDepartamento)
                    .addComponent(btnListarDepartamentos)
                    .addComponent(btnActualizarDepartamento))
                .addGap(84, 84, 84)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        panel.addTab("Departamentos", panelDepartamentos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 352, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDeptoActionPerformed
        
        String nombreDepto = txtNombreDepartamento.getText().trim();
        if(nombreDepto.isEmpty()){
            JOptionPane.showMessageDialog(this, "este campo no puede quedar vacio");
            return;
        }
        if(nombreDepto.length()>45){
            JOptionPane.showMessageDialog(this, "el nombre es demasiado largo(maximo 45 caracteres)");
            return;
        }
        if(nombreDepto.matches("^[a-zA-ZñÑáéíóúÁÉÍÓÚ ]+$"))
        try {
            Departamento depto = new Departamento();
            depto.setNombreDepartamento(nombreDepto);
            
            DepartamentoDAO dao = new DepartamentoDAO();
            dao.insertarNuevoDepartamento(depto);
            JOptionPane.showMessageDialog(this, "Departamento insertado exitosamente");
            txtNombreDepartamento.setText("");
             btnListarDepartamentosActionPerformed(null);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error en SQL" + e.getMessage());
        }
        
        

    }//GEN-LAST:event_btnGuardarDeptoActionPerformed

    private void btnActualizarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDepartamentoActionPerformed
        // TODO add your handling code here:
        if (idMemoria == -1) {
        JOptionPane.showMessageDialog(this, "Debe buscar un departamento antes de actualizar");
        return;
    }

    try {
        Departamento dep = new Departamento();
        dep.setIdDepartamento(idMemoria); // Usamos el ID que el buscador nos dejó [cite: 2026-01-12]
        dep.setNombreDepartamento(txtNombreDepartamento.getText().trim());

        DepartamentoDAO dao = new DepartamentoDAO();
        if (dao.actualizarDepartamento(dep)) { 
            JOptionPane.showMessageDialog(this, "¡Registro actualizado!");
            idMemoria = -1; // Limpiamos la memoria tras el éxito
            txtNombreDepartamento.setText("");
            // Aquí llamarías a cargarTabla() para que el usuario vea el cambio
        }
    } catch (SQLException e) { /* manejar error */ }
    }//GEN-LAST:event_btnActualizarDepartamentoActionPerformed

    private void btnListarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDepartamentosActionPerformed
        try {
            List<Departamento> lista = depDao.listarDepartamentos();
            if(lista.isEmpty()){
                System.out.println("lista esta");
            }else{
                System.out.println("Lista disponible");
                for (Departamento D: lista) {
                    System.out.println("ID " + D.getIdDepartamento()+ "\n nombre " + D.getNombreDepartamento());
                }
                 
            }
            
        } catch (SQLException ex) {
            System.out.println("Error en la conexion "+  ex.getMessage());
        }
        
        
        
    }//GEN-LAST:event_btnListarDepartamentosActionPerformed

    private void btnBuscarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDepartamentoActionPerformed
        String nombreBuscado = txtNombreDepartamento.getText().trim();
        if(nombreBuscado.isEmpty()){
            JOptionPane.showMessageDialog(this, "Este campo no puede quedar vacio");
            return;
        }
        try {
            DepartamentoDAO dao = new DepartamentoDAO();
            Departamento dep = dao.buscarDepartamentoPorNombre(txtNombreDepartamento.getText().trim());
        
        if (dep != null) {
            idMemoria = dep.getIdDepartamento(); // Marcamos el ID [cite: 2026-01-12]
            txtNombreDepartamento.setText(dep.getNombreDepartamento());
            JOptionPane.showMessageDialog(this, "Departamento listo para editar");
        } else {
            idMemoria = -1;
            JOptionPane.showMessageDialog(this, "No existe ese departamento");
        }
            
             
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error en sql, verifique su conexion" + e.getMessage());
            
            
        }
    }//GEN-LAST:event_btnBuscarDepartamentoActionPerformed

    private void btnEliminarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDepartamentoActionPerformed
        String nombrebuscado = txtNombreDepartamento.getText();
        if(nombrebuscado.isEmpty()){
            JOptionPane.showMessageDialog(this, "rellena el campo para eliminar");
            return;
        }
        try {
            DepartamentoDAO dao = new DepartamentoDAO();
            Departamento depto = dao.buscarDepartamentoPorNombre(nombrebuscado);
            if(depto != null){
                int confirmar = JOptionPane.showConfirmDialog(this, "¿SEguro que quieres eliminar " + depto.getNombreDepartamento() +
                        " (ID: " + depto.getIdDepartamento()+ "?");
                if(confirmar == JOptionPane.YES_OPTION){
                    boolean exito = dao.eliminarDepartamento(depto.getIdDepartamento());
                    if(exito){
                        JOptionPane.showMessageDialog(this, "Eliminado con exito");
                        
                        txtNombreDepartamento.setText("");
                        System.out.println("Nombre departamento" + depto.getNombreDepartamento());
                        System.out.println("Id departamento" + depto.getIdDepartamento());
                    }
                    
                }
            }else{
                JOptionPane.showMessageDialog(this, "No se encontro el departamento" + nombrebuscado);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error en la base de datos" + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarDepartamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarDepartamento;
    private javax.swing.JButton btnBuscarDepartamento;
    private javax.swing.JButton btnEliminarDepartamento;
    private javax.swing.JButton btnGuardarDepto;
    private javax.swing.JButton btnListarDepartamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JPanel panelDepartamentos;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JTextField txtNombreDepartamento;
    // End of variables declaration//GEN-END:variables
}
